<?php
?>
<!-- This is the container where your SDK's UI will be rendered. -->
<!-- <div id="mhcheckout-sdk-container-main" style="margin: 20px 0;">
  <p>Loading Secure SDK Component...</p>
</div> -->

<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>

<style>
  .form-input {
    border: 1px solid #d1d5dc;
    border-radius: 4px;
  }
</style>


<div class="flex flex-col items-center justify-center p-4">
  <div class="flex px-6 py-4 bg-white shadow-md rounded-lg flex-col w-full max-w-2xl">
    <h1 class="text-center">MoneyHash SDK</h1>

    <div id="intent-id" class="content">
      <label for="intent-id-input">Intent ID:</label>
      <span class="text-gray-500 flex gap-1 mb-3">
        insert intent id created using
        <a href="https://docs.moneyhash.io/reference/payment-intent-v11" target="_blank"
          class="text-blue-600 underline">
          MoneyHash API
        </a>
      </span>
      <input type="text" id="intent-id-input" class="w-full p-2 border border-gray-300 rounded"
        placeholder="Example: gEQlYKl" />

      <button id="load-intent-button"
        class="!mt-3 bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 cursor-pointer !flex items-center justify-center">
        Load Intent
      </button>
    </div>

    <div id="methods" class="content hidden">
      <h2 class="text-lg font-bold mb-2">Select Payment Method:</h2>
      <div id="express-methods"
        class="flex flex-col items-center justify-center border border-gray-300 rounded-lg p-2 mb-4">
        <h3 class="text-md font-semibold mb-2">Express checkout</h3>
      </div>
      <div id="payment-methods" class="flex flex-col gap-2"></div>
    </div>

    <div id="card-form" class="content hidden">
      <div class="grid grid-cols-2 gap-1">
        <div class="col-span-full">
          <div id="card-holder-name" class="form-input"></div>
          <div id="card-holder-name-error" class="text-red-500 invisible">error</div>
        </div>

        <div class="col-span-full">
          <div id="card-number" class="form-input"></div>
          <div id="card-number-error" class="text-red-500 invisible">error</div>
        </div>

        <div>
          <div id="card-expiry-month" class="form-input"></div>
          <div id="card-expiry-month-error" class="text-red-500 invisible">error</div>
        </div>

        <div>
          <div id="card-expiry-year" class="form-input"></div>
          <div id="card-expiry-year-error" class="text-red-500 invisible">error</div>
        </div>

        <div class="col-span-full">
          <div id="card-cvv" class="form-input"></div>
          <div id="card-cvv-error" class="text-red-500 invisible">error</div>
        </div>
      </div>

      <button id="submit-button"
        class="mt-2 bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 cursor-pointer w-full !flex items-center justify-center">
        Submit
      </button>
    </div>

    <div id="intent-status" class="content hidden flex flex-col items-center">
      <h2 class="mt-4 flex justify-center">
        <img id="intent-status-icon" src="" class="w-18 h-18"></img>
      </h2>
      <span id="intent-status-message" class="text-center"></span>
    </div>
  </div>
</div>

<!-- This script initializes our custom JavaScript component. -->
<script type="text/x-magento-init">
{
    "*": {
        "MHCheckout_SDK/js/sdk-initializer": {}
    }
}
</script>